apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: searchcollectorcustomizableconfigs.search.open-cluster-management.io
spec:
  group: search.open-cluster-management.io
  names:
    kind: SearchCollectorCustomizableConfig
    listKind: SearchCollectorCustomizableConfigList
    plural: searchcollectorcustomizableconfigs
    shortNames:
    - sccc
    singular: searchcollectorcustomizableconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: search-collector-customizable-config is the schema for the search-collector-customizable-configs
          API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: search-collector-customizable-config spec defines the configuration
              changes made to the resources and fields indexed by Search Collectors
            properties:
              allowedResources:
                description: Specifies a list of resources to be indexed by Search
                  Collectors
                items:
                  properties:
                    apiGroups:
                      description: Specifies apiGroups of resources to be indexed
                      items:
                        type: string
                      type: array
                    resources:
                      description: Specifies kinds of resources to be indexed
                      items:
                        type: string
                      type: array
                  required:
                  - apiGroups
                  - resources
                  type: object
                type: array
              collectFields:
                description: Specifies the additional fields to be indexed on resources
                  by Search Collectors
                items:
                  properties:
                    apiGroup:
                      description: Specifies apiGroup of resource to make the configuration
                        changes made to the resources and fields indexed by Search
                        Collectors
                      type: string
                    collectAdditionalPrinterColumnsPriority:
                      description: Specifies the priority on additionalPrinterColumns
                        for which to collect
                      type: integer
                    collectAnnotations:
                      description: Specifies to collect annotations for the resource
                      type: boolean
                    collectConditions:
                      description: Specifies to collect status conditions for the
                        resource
                      type: boolean
                    fields:
                      description: Specifies the fields on the resource to index by
                        Search Collectors
                      items:
                        properties:
                          displayName:
                            type: string
                          jsonPath:
                            type: string
                          name:
                            description: |-
                              Specified the name of the collected item on the resource.
                              The system prepends a special character to this name to avoid collisions with built in collected attributes
                            type: string
                          priority:
                            type: integer
                          type:
                            description: Data type of resource field to be indexed
                              by Search Collectors. Default is a string
                            enum:
                            - DataTypeBytes
                            - DataTypeSlice
                            - DataTypeString
                            - DataTypeNumber
                            - DataTypeMapString
                            type: string
                        required:
                        - name
                        - jsonPath
                        type: object
                      type: array
                    inNamespace:
                      description: Specifies the namespace where resources are to
                        be indexed by Search Collectors
                      items:
                        type: string
                      type: array
                    kind:
                      description: Specifies the Kind of resource to make the configuration
                        changes made to the resources and fields indexed by Search
                        Collectors
                      type: string
                    notInNamespace:
                      description: Specifies the namespace where the resources are
                        not to be indexed by Search Collectors
                      items:
                        type: string
                      type: array
                  type: object
                type: array
              deniedResources:
                description: Specifies a list of resources not to be indexed by Search
                  Collectors
                items:
                  properties:
                    apiGroups:
                      description: Specifies apiGroups of resources not to be indexed
                      items:
                        type: string
                      type: array
                    resources:
                      description: Specified kinds of resources not to be indexed
                      items:
                        type: string
                      type: array
                  required:
                  - apiGroups
                  - resources
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
