apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: collectionconfigs.search.open-cluster-management.io
spec:
  group: search.open-cluster-management.io
  scope: Namespaced
  names:
    plural: collectionconfigs
    singular: collectionconfig
    listKind: CollectionConfigList
    kind: CollectionConfig
    shortNames: [sccc]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: collection-config is the schema for the collection-configs API.
          type: object
          properties:
            apiVersion:
              description: |-
                APIVersion defines the versioned schema of this representation of an object.
                Servers should convert recognized schemas to the latest internal value, and
                may reject unrecognized values.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: |-
                Kind is a string value representing the REST resource this object represents.
                Servers may infer this from the endpoint the client submits requests to.
                Cannot be updated.
                In CamelCase.
                More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              type: object
            spec:
              description: collection-config spec defines the configuration changes made to the resources and fields indexed by Search Collectors
              type: object
              properties:
                collectNamespaces:
                  description: Specified the namespaces where resources are to be indexed by Search Collectors
                  type: object
                  properties:
                    namespaceSelector:
                      type: object
                      properties:
                        include:
                          description: List of namespace names to include
                          type: array
                          items:
                            type: string
                        exclude:
                          description: List of namespace names to exclude
                          type: array
                          items:
                            type: string
                        matchExpressions:
                          description: Label selector expressions for matching namespaces
                          type: array
                          items:
                            type: object
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                type: array
                                items:
                                  type: string
                        matchLabels:
                          description: Label selector for matching namespaces
                          type: object
                          additionalProperties:
                            type: string
                collectionRules:
                  description: Defines a list of rules for collecting resources and specific fields.
                  type: array
                  items:
                    type: object
                    properties:
                      action:
                        description: Defines whether to Include (collect) or Exclude (deny collection) resources matching the selector.
                        type: string
                        enum: [Include, Exclude]
                      resourceSelector:
                        description: Specifies which resources this rule applies to.
                        type: object
                        properties:
                          apiGroups:
                            description: Specifies apiGroups of resources.
                            type: array
                            items:
                              type: string
                          kinds:
                            description: Specifies kinds of resources.
                            type: array
                            items:
                              type: string
                        required:
                          - apiGroups
                          - kinds
                      fields:
                        description: Specifies the additional fields on the resource to index by Search Collectors.
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              description: Specified the name of the collected item on the resource.
                              type: string
                            jsonPath:
                              type: string
                            type:
                              description: Data type of resource field to be indexed by Search Collectors. Default is a string.
                              type: string
                              enum: [DataTypeBytes, DataTypeSlice, DataTypeString, DataTypeNumber, DataTypeMapString]
                            displayName:
                              type: string
                          required:
                            - name
                            - jsonPath
                      collectAnnotations:
                        description: Specifies to collect annotations for the resource.
                        type: boolean
                      collectConditions:
                        description: Specifies to collect status conditions for the resource.
                        type: boolean
                      collectAdditionalPrinterColumnsPriority:
                        description: Specifies the priority on additionalPrinterColumns for which to collect.
                        type: integer
