---
{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "controller.fullname" . }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "controller.fullname" . }}
    component: search
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 60s
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      component: "search"
{{- end }}
