---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "search.fullname" . }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "search.fullname" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    addon.open-cluster-management.io/hosted-manifest-location: hosting
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 60s
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "search.fullname" . }}
      release: {{ .Release.Name }}
